drop database if exists kinoCMS;
create database kinoCMS character set utf8;

create table advertisement (advertisement_id bigint not null auto_increment, description text, main_image varchar(255), name varchar(255), seos_id bigint, primary key (advertisement_id));
create table advertisement_image (advertisement_image_id bigint not null auto_increment, image varchar(255), advertisement_id bigint, primary key (advertisement_image_id));
create table cart (cart_id bigint not null auto_increment, primary key (cart_id));
create table cinema (cinema_id bigint not null auto_increment, description text, logo_image varchar(255), main_image varchar(255), name varchar(255), rules varchar(255), upper_banner_image varchar(255), seos_id bigint, primary key (cinema_id));
create table cinema_image (cinema_image_id bigint not null auto_increment, image varchar(255), cinema_id bigint, primary key (cinema_image_id));
create table city (city_id bigint not null auto_increment, name varchar(255), primary key (city_id));
create table contact (contact_id bigint not null auto_increment, address varchar(255), cinema_name varchar(255), logo_image varchar(255), map_coordinates varchar(255), contacts_page_id bigint, primary key (contact_id));
create table contacts_page (contacts_page_id bigint not null auto_increment, active bit, creation_date datetime, name varchar(255), seos_id bigint, primary key (contacts_page_id));
create table hall (hall_id bigint not null auto_increment, banner_image varchar(255), count_of_tickets integer, description text, name varchar(255), schema_image varchar(255), cinema_id bigint, seos_id bigint, primary key (hall_id));
create table hall_image (hall_image_id bigint not null auto_increment, image varchar(255), hall_id bigint, primary key (hall_image_id));
create table main_page (main_page_id bigint not null auto_increment, active bit, creation_date datetime, first_phone varchar(255), name varchar(255), second_phone varchar(255), seo_text varchar(255), seos_id bigint, primary key (main_page_id));
create table main_page_image (movie_image_id bigint not null auto_increment, image varchar(255), main_page_id bigint, primary key (movie_image_id));
create table movie (movie_id bigint not null auto_increment, date_finish date, date_release date, description text, main_image varchar(255), name varchar(255), trailer_link varchar(255), seos_id bigint, primary key (movie_id));
create table movie_image (movie_image_id bigint not null auto_increment, image varchar(255), movie_id bigint, primary key (movie_image_id));
create table movie_type (movie_type_id bigint not null auto_increment, type varchar(255), movie_id bigint, primary key (movie_type_id));
create table movie_types (movie_id bigint not null, movie_type_id bigint not null);
create table news (news_id bigint not null auto_increment, active bit, creation_date datetime, description text, main_image varchar(255), name varchar(255), publish_date datetime, video_link varchar(255), seos_id bigint, primary key (news_id));
create table news_image (news_image_id bigint not null auto_increment, image varchar(255), news_id bigint, primary key (news_image_id));
create table orders (order_id bigint not null auto_increment, create_data_order datetime, finished bit, user_user_id bigint, primary key (order_id));
create table page (page_id bigint not null auto_increment, active bit, creation_date datetime, description text, main_image varchar(255), name varchar(255), seos_id bigint, primary key (page_id));
create table page_image (page_image_id bigint not null auto_increment, image varchar(255), page_id bigint, primary key (page_image_id));
create table promotion (promotion_id bigint not null auto_increment, active bit, creation_date datetime, description text, main_image varchar(255), name varchar(255), publish_date datetime, video_link varchar(255), seos_id bigint, primary key (promotion_id));
create table promotion_image (promotion_image_id bigint not null auto_increment, image varchar(255), promotion_id bigint, primary key (promotion_image_id));
create table seo (seo_id bigint not null auto_increment, description text, keywords varchar(255), title varchar(255), url varchar(255), primary key (seo_id));
create table session (session_id bigint not null auto_increment, date datetime, hall_id bigint, movie_id bigint, primary key (session_id));
create table ticket (ticket_id bigint not null auto_increment, create_ticket datetime, is_booked bit, is_purchased bit, price bigint, is_bought bigint, session_id bigint, primary key (ticket_id));
create table ticket_count (ticket_count_id bigint not null auto_increment, count integer, cart_cart_id bigint, order_order_id bigint, ticket_ticket_id bigint, primary key (ticket_count_id));
create table user (user_id bigint not null auto_increment, address varchar(255), birthday date, date_of_registration datetime, email varchar(255), first_name varchar(255), language varchar(255), last_name varchar(255), login varchar(255), password varchar(20), phone varchar(255), role_type varchar(255), sex varchar(255), cart_cart_id bigint, city_id bigint, primary key (user_id));
create table user_favorites (user_list_user_id bigint not null, favorites_ticket_id bigint not null);
create table vip_hall_image (vip_hall_image_id bigint not null auto_increment, image varchar(255), vip_hall_page_id bigint, primary key (vip_hall_image_id));
create table vip_hall_page (vip_hall_page_id bigint not null auto_increment, description varchar(255), main_image varchar(255), schema_image varchar(255), seos_id bigint, primary key (vip_hall_page_id));
alter table movie_type drop index UK_ibukwyhx2yr81uubycfm5w9ku;
alter table movie_type add constraint UK_ibukwyhx2yr81uubycfm5w9ku unique (type);
alter table user drop index UK_ob8kqyqqgmefl0aco34akdtpe;
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user drop index UK_ew1hvam8uwaknuaellwhqchhb;
alter table user add constraint UK_ew1hvam8uwaknuaellwhqchhb unique (login);
alter table advertisement add constraint FKi073me75pyw49uq2y3lswp8ww foreign key (seos_id) references seo (seo_id);
alter table advertisement_image add constraint FKnvtediftieet4yv9525kv3gt1 foreign key (advertisement_id) references advertisement (advertisement_id);
alter table cinema add constraint FK19ikit6xpt3akertpg0vm7hkk foreign key (seos_id) references seo (seo_id);
alter table cinema_image add constraint FKqb1pjp6n9bnok2767evedjmh1 foreign key (cinema_id) references cinema (cinema_id);
alter table contact add constraint FKro9vrnlin4hdu2mctrxl71byj foreign key (contacts_page_id) references contacts_page (contacts_page_id);
alter table contacts_page add constraint FK46r4wkr53u2ybcbqekpcytpx0 foreign key (seos_id) references seo (seo_id);
alter table hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (cinema_id);
alter table hall add constraint FK5y3m1i2vxly44yo7wd5n15ke3 foreign key (seos_id) references seo (seo_id);
alter table hall_image add constraint FKlam285smfu6djw1w1n6p1gfue foreign key (hall_id) references hall (hall_id);
alter table main_page add constraint FKt9twvittjudtata7tdbmc1fm2 foreign key (seos_id) references seo (seo_id);
alter table main_page_image add constraint FKe7ipqu13ubepfoyp3eem8jp50 foreign key (main_page_id) references main_page (main_page_id);
alter table movie add constraint FK9gc893g1bdlxb7o97h9dyp5bm foreign key (seos_id) references seo (seo_id);
alter table movie_image add constraint FK171int0q4s8nv3exygxte7xls foreign key (movie_id) references movie (movie_id);
alter table movie_type add constraint FKcta7x8y5i5nk033nalychnpjp foreign key (movie_id) references movie (movie_id);
alter table movie_types add constraint FKo8vw8ijjrkjr2yt031m7md9ce foreign key (movie_type_id) references movie_type (movie_type_id);
alter table movie_types add constraint FKf0psbvhm94d257te7bnc1x31w foreign key (movie_id) references movie (movie_id);
alter table news add constraint FK61wgkhw0cib88x6lu1gev784d foreign key (seos_id) references seo (seo_id);
alter table news_image add constraint FKhwajir19rbhvdif5as4g6wcwf foreign key (news_id) references news (news_id);
alter table orders add constraint FKcooejujh32cpgw33d02snbufy foreign key (user_user_id) references user (user_id);
alter table page add constraint FKodq3med4fjy6lxdwr5bgm72ds foreign key (seos_id) references seo (seo_id);
alter table page_image add constraint FKencjs4bkar23r0040n8v96o3k foreign key (page_id) references page (page_id);
alter table promotion add constraint FKi1v9vhyph37c5cnt88y44hbi7 foreign key (seos_id) references seo (seo_id);
alter table promotion_image add constraint FK1kk51vlapwvuxvgsptcnehh70 foreign key (promotion_id) references promotion (promotion_id);
alter table session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (hall_id);
alter table session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (movie_id);
alter table ticket add constraint FKp9h4d1v24ttxebch41fcv8hy2 foreign key (is_bought) references user (user_id);
alter table ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (session_id);
alter table ticket_count add constraint FK21f8qg5ywosvebm18pgctob80 foreign key (cart_cart_id) references cart (cart_id);
alter table ticket_count add constraint FK6qn166i6p6l8s087rg142uri9 foreign key (order_order_id) references orders (order_id);
alter table ticket_count add constraint FK4obiwb21gd7pbdh9ab3l0wom1 foreign key (ticket_ticket_id) references ticket (ticket_id);
alter table user add constraint FKak34gd6gbtvduhkfsmkh9nqy4 foreign key (cart_cart_id) references cart (cart_id);
alter table user add constraint FK29eqyw0gxw5r4f1ommy11nd9i foreign key (city_id) references city (city_id);
alter table user_favorites add constraint FKqcdl1yk60bvxhout346w7l4cn foreign key (favorites_ticket_id) references ticket (ticket_id);
alter table user_favorites add constraint FK56exvek91o61uvfpppjnc8m9x foreign key (user_list_user_id) references user (user_id);
alter table vip_hall_image add constraint FK4t8q61exgsstvuek4enoaufmk foreign key (vip_hall_page_id) references vip_hall_page (vip_hall_page_id);
alter table vip_hall_page add constraint FKhf401grptvl7xkoi9c5nfu5wc foreign key (seos_id) references seo (seo_id);